---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum:
      name=docker
      state=present
  - name: start docker
    service:
      name=docker
      state=started
  - name: Pull an image
    docker_image:
      name: devopsedu/webapp
      source: pull
  - name: run the image
    command: docker run --name -itd -P devopsedu/webapp

